# Generated by Django 4.2.1 on 2023-05-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.TextField()),
                ('text_content', models.TextField()),
                ('text_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
