# Generated by Django 4.2.1 on 2023-05-09 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('CO', 'Code'), ('TE', 'Text')], default='CO', max_length=2)),
                ('code_content', models.TextField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('text_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'sequence'],
                'unique_together': {('user', 'sequence')},
            },
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
