# Generated by Django 4.2.1 on 2023-05-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_content_delete_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='text_image',
            new_name='image_content',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('CO', 'Code'), ('TE', 'Text'), ('IMG', 'Image'), ('IMG', 'Image')], default='CO', max_length=3),
        ),
    ]
