# Generated by Django 4.2.1 on 2023-05-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_codecontent_label_codecontent_submit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codecontent',
            old_name='submit',
            new_name='goes',
        ),
        migrations.RenameField(
            model_name='imagecontent',
            old_name='submit',
            new_name='goes',
        ),
        migrations.RenameField(
            model_name='textcontent',
            old_name='submit',
            new_name='goes',
        ),
    ]
