# Generated by Django 4.2.1 on 2023-05-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_submit_codecontent_goes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codecontent',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='imagecontent',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'ordering': ['label']},
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
    ]
