# Generated by Django 4.2.1 on 2023-05-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_codecontent_options_alter_imagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ridership', models.IntegerField()),
                ('route_number', models.CharField(max_length=200)),
                ('standard_bus_station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=200)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
    ]
