# Generated by Django 4.2.1 on 2023-05-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_map_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusData',
            new_name='Map_00',
        ),
        migrations.RenameModel(
            old_name='Map_1',
            new_name='Map_01',
        ),
    ]
