# Generated by Django 4.2.1 on 2023-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_recommend_02'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_02',
            name='label',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
