# Generated by Django 4.2.1 on 2023-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_recommend_02_avg_bus_stop_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_02',
            name='nearest_tourist_spot_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
