# Generated by Django 4.2.1 on 2023-05-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_recommend_02_nearest_tourist_spot_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_02new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('competing_hotels_count', models.IntegerField(null=True)),
                ('competing_hotels_min_distance', models.FloatField(null=True)),
                ('competing_hotels_max_distance', models.FloatField(null=True)),
                ('competing_hotels_avg_distance', models.FloatField(null=True)),
                ('bus_stops_count', models.IntegerField(null=True)),
                ('subway_stations_count', models.IntegerField(null=True)),
                ('nearest_bus_stop_distance', models.FloatField(null=True)),
                ('avg_bus_stop_distance', models.FloatField(null=True)),
                ('nearest_subway_station_distance', models.FloatField(null=True)),
                ('avg_subway_station_distance', models.FloatField(null=True)),
                ('monthly_average_boarding_traffic', models.FloatField(null=True)),
                ('monthly_average_alighting_traffic', models.FloatField(null=True)),
                ('monthly_total_traffic', models.FloatField(null=True)),
                ('tourist_spots_count', models.IntegerField(null=True)),
                ('shopping_malls_count', models.IntegerField(null=True)),
                ('nearest_tourist_spot_distance', models.FloatField(blank=True, null=True)),
                ('avg_tourist_spot_distance', models.FloatField(null=True)),
                ('nearest_shopping_mall_distance', models.FloatField(null=True)),
                ('avg_shopping_mall_distance', models.FloatField(null=True)),
                ('label', models.IntegerField(null=True)),
            ],
        ),
    ]
