# Generated by Django 4.2.1 on 2023-05-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_recommend_02new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sankey_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_region', models.CharField(max_length=255)),
                ('destination_Region', models.CharField(max_length=255)),
                ('inflow_outflow_Ratio', models.FloatField(null=True)),
                ('flow_direction_code', models.IntegerField(null=True)),
            ],
        ),
    ]
