# Generated by Django 4.2.1 on 2023-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_sankey_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('tourist_spot', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('category_large', models.CharField(max_length=50)),
                ('category_medium', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
